name: check 42 norminette

on:
  push:
  pull_request:
jobs:
  check_42_norm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install 42 norminette
        run: |
          sudo apt update
          sudo apt install python3 -y
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --upgrade norminette
          
      - name: check for 42 norminette requirements 
        run: |
          echo checking files: $(git ls-files)
          norminette .
      
  check_compile_error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check for compilation errors
        run: |
          sudo apt update
          sudo apt install build-essential -y
          echo checking files: $(git ls-files)
          for f in $(find . -name \*.c); do gcc -Wall -Wextra -Werror -fsyntax-only $f; done

  
